require("cx.plugins-setup")
require("cx.core.options")
require("cx.core.keymaps")
-- require("cx.core.colorscheme")
require("cx.core.colorscheme.base16")
-- require("cx.core.colorscheme.init")
require("cx.plugins.comment")
require("cx.plugins.nvim-tree")
require("cx.plugins.lualine")
require("cx.plugins.telescope")
-- require("cx.plugins.harpoon") -- 如果需要 修改配置就加载
require("cx.plugins.nvim-cmp")
require("cx.plugins.luasnip")
require("cx.plugins.lsp.mason")
require("cx.plugins.lsp.lspconfig")
require("cx.plugins.lsp.lspsaga")
require("cx.plugins.lsp.null-ls")
require("cx.plugins.autopair")
require("cx.plugins.treesitter")
require("cx.plugins.gitsigns")
require("cx.plugins.todo-comments")
require("cx.plugins.git")
require("cx.plugins.colorizer")
-- hologram currently not working
-- require("cx.plugins.hologram")
-- require("cx.plugins.lsp-color")
-- require("cx.plugins.bufferline")
