require("core.options")
require("core.keymaps")
require("core.lazy")
require("core.colorscheme.base16")
-- require("core.colorscheme")
-- -- require("core.colorscheme.init")
-- require("plugins.comment")
-- require("plugins.nvim-tree")
-- require("plugins.lualine")
-- require("plugins.telescope")
-- -- require("plugins.harpoon") -- 如果需要 修改配置就加载
-- require("plugins.nvim-cmp")
-- require("plugins.luasnip")
-- require("plugins.lsp.mason")
-- require("plugins.lsp.lspconfig")
-- require("plugins.lsp.lspsaga")
-- require("plugins.lsp.null-ls")
-- require("plugins.autopair")
-- require("plugins.treesitter")
-- require("plugins.gitsigns")
-- require("plugins.todo-comments")
-- require("plugins.git")
-- require("plugins.colorizer")
-- hologram currently not working
-- require("plugins.hologram")
-- require("plugins.bufferline")
-- require("plugins.lsp-color")
